/**
 * Centralised static UI copy.
 *
 * Only fixed interface labels live here. Portfolio content (profile, projects,
 * skills, experience, service cards, links) is loaded from Supabase.
 */
export const AppStrings = {
  meta: {
    siteName: 'Muhammad Musa',
    defaultTitle: 'Muhammad Musa — Mobile Application Developer',
    titleTemplate: '%s | Muhammad Musa',
    defaultDescription:
      'Portfolio of Muhammad Musa, a mobile application developer building Flutter, Firebase, POS and AI/ML powered iOS & Android apps.',
    projectsTitle: 'Projects',
    projectsDescription: 'Mobile apps, POS systems and production products built by Muhammad Musa.',
    contactTitle: 'Tell Me Your Idea',
    contactDescription: 'Share your project idea and get a response about scope, timeline and next steps.',
  },
  a11y: {
    skipToContent: 'Skip to content',
    primaryNav: 'Primary navigation',
    mobileNav: 'Mobile navigation',
    footerNav: 'Footer navigation',
    projectNav: 'Project navigation',
    openMenu: 'Open menu',
    closeMenu: 'Close menu',
    homeLink: 'Go to homepage',
    projectLogo: (name: string) => `${name} logo`,
    socialLink: (platform: string) => `Visit my ${platform} profile`,
    previousImage: 'Previous screenshot',
    nextImage: 'Next screenshot',
    closeGallery: 'Close gallery',
    openImage: (index: number) => `Open screenshot ${index}`,
  },
  nav: {
    home: 'Home',
    about: 'About',
    projects: 'Projects',
    skills: 'Skills',
    experience: 'Experience',
    contact: 'Contact',
    downloadCv: 'Download CV',
  },
  hero: {
    viewProjects: 'View Projects',
    contactMe: 'Contact Me',
    statExperience: 'Years Experience',
    statProjects: 'Projects Completed',
    statUsers: 'Users Reached',
    portraitAlt: (name: string) => `Portrait of ${name}`,
    platformCardLabel: 'Platforms I ship to',
  },
  skills: {
    eyebrowLine1: 'My Core',
    eyebrowLine2: 'Skills & Technologies',
    emptyTechnologies: 'Technologies will appear here soon.',
  },
  projects: {
    eyebrow: 'Featured Projects',
    headingLead: 'Some of My',
    headingAccent: 'Recent Work',
    viewAll: 'View All Projects',
    allEyebrow: 'Portfolio',
    allHeadingLead: 'All',
    allHeadingAccent: 'Projects',
    allDescription: 'Production apps, POS platforms and products I have designed, built and shipped.',
    empty: 'No projects have been published yet.',
    emptyHint: 'Projects added in Supabase will appear here automatically.',
  },
  projectDetail: {
    backToProjects: 'All Projects',
    overview: 'Overview',
    myRole: 'My Role',
    techStack: 'Technology Stack',
    gallery: 'Screenshots',
    highlights: 'Key Features',
    details: 'Project Details',
    status: 'Status',
    projectType: 'Project Type',
    client: 'Company / Client',
    appStore: 'App Store',
    playStore: 'Google Play',
    github: 'View on GitHub',
    website: 'Visit Website',
    previous: 'Previous Project',
    next: 'Next Project',
    related: 'More Projects',
    noGallery: 'Screenshots for this project are coming soon.',
  },
  about: {
    eyebrow: 'About Me',
    portraitAlt: (name: string) => `${name} smiling`,
  },
  experience: {
    eyebrow: 'Experience',
    headingLead: 'Where I Have',
    headingAccent: 'Built & Shipped',
    present: 'Present',
    toolbox: 'Toolbox',
    empty: 'Experience details will be published soon.',
  },
  cta: {
    eyebrow: "Let's Work Together",
    heading: 'Have a Project in Mind?',
    description:
      "I'm always open to discussing new opportunities, exciting ideas, or long-term collaborations. Let's build something amazing together!",
    contactMe: 'Contact Me',
    downloadCv: 'Download CV',
    tellIdea: 'Tell Me Your Idea',
    handwritten: ["Let's Build", 'Something Great', 'Together'],
  },
  inquiry: {
    eyebrow: 'Start a Project',
    headingLead: 'Tell Me',
    headingAccent: 'Your Idea',
    description:
      'Share a few details about what you want to build. I read every submission personally and usually reply within two working days.',
    directContact: 'Prefer email?',
    sections: {
      about: 'About You',
      project: 'About the Project',
      logistics: 'Budget & Timeline',
    },
    fields: {
      name: 'Full name',
      email: 'Email address',
      phone: 'Phone',
      company: 'Company',
      projectTitle: 'Project title',
      projectType: 'Project type',
      budgetRange: 'Budget range',
      timeline: 'Timeline',
      ideaSummary: 'Describe your idea',
      requiredServices: 'Services you need',
      preferredContactMethod: 'Preferred contact method',
      website: 'Website',
    },
    optional: '(optional)',
    placeholders: {
      name: 'Jane Doe',
      email: 'jane@company.com',
      phone: '+1 555 000 0000',
      company: 'Company name',
      projectTitle: 'e.g. Restaurant ordering app',
      ideaSummary: 'What problem does it solve, who uses it, and which features matter most?',
      select: 'Select an option',
    },
    options: {
      projectType: [
        'New mobile app',
        'Existing app improvement',
        'POS / retail system',
        'MVP / prototype',
        'Backend & integrations',
        'Other',
      ],
      budgetRange: ['Under $1,000', '$1,000 – $5,000', '$5,000 – $15,000', '$15,000+', 'Not sure yet'],
      timeline: ['ASAP', '1 – 3 months', '3 – 6 months', '6+ months', 'Flexible'],
      requiredServices: [
        'Flutter app development',
        'Android / iOS native',
        'UI implementation',
        'Firebase / backend',
        'App Store & Play Store release',
        'AI/ML integration',
        'Maintenance & support',
      ],
      preferredContactMethod: ['Email', 'Phone', 'WhatsApp'],
    },
    submit: 'Submit Your Idea',
    submitting: 'Sending…',
    successTitle: 'Thank you — your idea is on its way!',
    successBody: "I've received your project details and will get back to you soon.",
    sendAnother: 'Submit another idea',
    validation: {
      nameRequired: 'Please enter your name.',
      nameTooLong: 'Name is too long.',
      emailInvalid: 'Please enter a valid email address.',
      phoneInvalid: 'Please enter a valid phone number.',
      textTooLong: 'This field is too long.',
      ideaTooShort: 'Please describe your idea in at least 20 characters.',
      ideaTooLong: 'Please keep your description under 4000 characters.',
      invalidOption: 'Please choose one of the available options.',
    },
    errors: {
      generic: 'Something went wrong while sending your idea. Please try again.',
      network: 'Could not reach the server. Check your connection and try again.',
      rateLimited: 'You have sent several requests recently. Please try again a little later.',
      invalid: 'Please fix the highlighted fields and try again.',
      unavailable: 'Submissions are temporarily unavailable. Please email me directly instead.',
    },
  },
  footer: {
    rights: 'All rights reserved.',
    builtWith: 'Built with Next.js & Supabase',
  },
  states: {
    loading: 'Loading…',
    errorTitle: 'Something went wrong',
    errorBody: 'This content could not be loaded right now. Please try again in a moment.',
    retry: 'Try again',
    unavailableTitle: 'Content is temporarily unavailable',
    unavailableBody: 'The portfolio data source could not be reached. Please refresh in a moment.',
    notFoundTitle: 'Page not found',
    notFoundBody: "The page you're looking for doesn't exist or may have moved.",
    projectNotFoundTitle: 'Project not found',
    backHome: 'Back to Home',
    imageUnavailable: 'Image unavailable',
  },
} as const;
